# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather_widget_flex_scaling.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(705, 485)
        self.horizontalLayout_26 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lbl_cur_icon = weatherIcon(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_cur_icon.sizePolicy().hasHeightForWidth())
        self.lbl_cur_icon.setSizePolicy(sizePolicy)
        self.lbl_cur_icon.setMinimumSize(QtCore.QSize(100, 100))
        self.lbl_cur_icon.setMaximumSize(QtCore.QSize(211, 211))
        self.lbl_cur_icon.setSizeIncrement(QtCore.QSize(0, 0))
        self.lbl_cur_icon.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_cur_icon.setText(_fromUtf8(""))
        self.lbl_cur_icon.setPixmap(QtGui.QPixmap(_fromUtf8("../../res/weather/icon/NA/na.png")))
        self.lbl_cur_icon.setScaledContents(False)
        self.lbl_cur_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cur_icon.setObjectName(_fromUtf8("lbl_cur_icon"))
        self.horizontalLayout_2.addWidget(self.lbl_cur_icon)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(11, 41))
        self.label_3.setMaximumSize(QtCore.QSize(11, 41))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setPixmap(QtGui.QPixmap(_fromUtf8(":/thermometer.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lbl_cur_temp = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(34)
        self.lbl_cur_temp.setFont(font)
        self.lbl_cur_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_cur_temp.setObjectName(_fromUtf8("lbl_cur_temp"))
        self.horizontalLayout_3.addWidget(self.lbl_cur_temp)
        self.label_7 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.lbl_cur_temp_feel = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(34)
        self.lbl_cur_temp_feel.setFont(font)
        self.lbl_cur_temp_feel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_cur_temp_feel.setObjectName(_fromUtf8("lbl_cur_temp_feel"))
        self.horizontalLayout_3.addWidget(self.lbl_cur_temp_feel)
        self.label_9 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_3.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(31, 34))
        self.label_4.setMaximumSize(QtCore.QSize(31, 34))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/umbrella.png")))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lbl_cur_rain = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_cur_rain.setFont(font)
        self.lbl_cur_rain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_cur_rain.setObjectName(_fromUtf8("lbl_cur_rain"))
        self.horizontalLayout_4.addWidget(self.lbl_cur_rain)
        self.label_11 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(31, 34))
        self.label_5.setMaximumSize(QtCore.QSize(31, 34))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/wind.png")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lbl_cur_wind = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lbl_cur_wind.setFont(font)
        self.lbl_cur_wind.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_cur_wind.setObjectName(_fromUtf8("lbl_cur_wind"))
        self.horizontalLayout_5.addWidget(self.lbl_cur_wind)
        self.label_13 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_5.addWidget(self.label_13)
        self.lbl_cur_wind_direction = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.lbl_cur_wind_direction.setFont(font)
        self.lbl_cur_wind_direction.setObjectName(_fromUtf8("lbl_cur_wind_direction"))
        self.horizontalLayout_5.addWidget(self.lbl_cur_wind_direction)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 2)
        self.horizontalLayout_5.setStretch(3, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.lbl_cur_sunrise = Scaling_QLabel(Form)
        self.lbl_cur_sunrise.setObjectName(_fromUtf8("lbl_cur_sunrise"))
        self.horizontalLayout_6.addWidget(self.lbl_cur_sunrise)
        self.label_66 = QtGui.QLabel(Form)
        self.label_66.setMinimumSize(QtCore.QSize(75, 31))
        self.label_66.setMaximumSize(QtCore.QSize(75, 31))
        self.label_66.setText(_fromUtf8(""))
        self.label_66.setPixmap(QtGui.QPixmap(_fromUtf8(":/sunrise.png")))
        self.label_66.setScaledContents(True)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout_6.addWidget(self.label_66)
        self.lbl_cur_sunset = Scaling_QLabel(Form)
        self.lbl_cur_sunset.setObjectName(_fromUtf8("lbl_cur_sunset"))
        self.horizontalLayout_6.addWidget(self.lbl_cur_sunset)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout.setStretch(5, 2)
        self.horizontalLayout_25.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_25.addWidget(self.line)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.label_15 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_7.addWidget(self.label_15)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_19 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_6.addWidget(self.label_19)
        spacerItem7 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.lbl_day_0_icon = weatherIcon(Form)
        self.lbl_day_0_icon.setMinimumSize(QtCore.QSize(56, 46))
        self.lbl_day_0_icon.setMaximumSize(QtCore.QSize(71, 61))
        self.lbl_day_0_icon.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_day_0_icon.setText(_fromUtf8(""))
        self.lbl_day_0_icon.setPixmap(QtGui.QPixmap(_fromUtf8("../../res/weather/icon/NA/na.png")))
        self.lbl_day_0_icon.setScaledContents(False)
        self.lbl_day_0_icon.setObjectName(_fromUtf8("lbl_day_0_icon"))
        self.horizontalLayout_10.addWidget(self.lbl_day_0_icon)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_22 = QtGui.QLabel(Form)
        self.label_22.setMinimumSize(QtCore.QSize(8, 21))
        self.label_22.setMaximumSize(QtCore.QSize(8, 21))
        self.label_22.setText(_fromUtf8(""))
        self.label_22.setPixmap(QtGui.QPixmap(_fromUtf8(":/thermometer.png")))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_12.addWidget(self.label_22)
        self.lbl_day_0_temp = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_day_0_temp.setFont(font)
        self.lbl_day_0_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_day_0_temp.setObjectName(_fromUtf8("lbl_day_0_temp"))
        self.horizontalLayout_12.addWidget(self.lbl_day_0_temp)
        self.label_30 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_12.addWidget(self.label_30)
        self.label_23 = QtGui.QLabel(Form)
        self.label_23.setMinimumSize(QtCore.QSize(18, 18))
        self.label_23.setMaximumSize(QtCore.QSize(18, 18))
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setPixmap(QtGui.QPixmap(_fromUtf8(":/umbrella.png")))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_12.addWidget(self.label_23)
        self.lbl_day_0_rain = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_day_0_rain.setFont(font)
        self.lbl_day_0_rain.setObjectName(_fromUtf8("lbl_day_0_rain"))
        self.horizontalLayout_12.addWidget(self.lbl_day_0_rain)
        self.label_31 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_12.addWidget(self.label_31)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_22.addLayout(self.verticalLayout_8)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_20 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_7.addWidget(self.label_20)
        spacerItem9 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.lbl_night_0_icon = weatherIcon(Form)
        self.lbl_night_0_icon.setMinimumSize(QtCore.QSize(56, 46))
        self.lbl_night_0_icon.setMaximumSize(QtCore.QSize(71, 61))
        self.lbl_night_0_icon.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_night_0_icon.setText(_fromUtf8(""))
        self.lbl_night_0_icon.setPixmap(QtGui.QPixmap(_fromUtf8("../../res/weather/icon/NA/na.png")))
        self.lbl_night_0_icon.setScaledContents(False)
        self.lbl_night_0_icon.setObjectName(_fromUtf8("lbl_night_0_icon"))
        self.horizontalLayout_11.addWidget(self.lbl_night_0_icon)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_24 = QtGui.QLabel(Form)
        self.label_24.setMinimumSize(QtCore.QSize(8, 21))
        self.label_24.setMaximumSize(QtCore.QSize(8, 21))
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setPixmap(QtGui.QPixmap(_fromUtf8(":/thermometer.png")))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_13.addWidget(self.label_24)
        self.lbl_night_0_temp = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_night_0_temp.setFont(font)
        self.lbl_night_0_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_night_0_temp.setObjectName(_fromUtf8("lbl_night_0_temp"))
        self.horizontalLayout_13.addWidget(self.lbl_night_0_temp)
        self.label_32 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_13.addWidget(self.label_32)
        self.label_25 = QtGui.QLabel(Form)
        self.label_25.setMinimumSize(QtCore.QSize(18, 18))
        self.label_25.setMaximumSize(QtCore.QSize(18, 18))
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setPixmap(QtGui.QPixmap(_fromUtf8(":/umbrella.png")))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_13.addWidget(self.label_25)
        self.lbl_night_0_rain = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_night_0_rain.setFont(font)
        self.lbl_night_0_rain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_night_0_rain.setObjectName(_fromUtf8("lbl_night_0_rain"))
        self.horizontalLayout_13.addWidget(self.lbl_night_0_rain)
        self.label_33 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_13.addWidget(self.label_33)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_22.addLayout(self.verticalLayout_9)
        self.verticalLayout_16.addLayout(self.horizontalLayout_22)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_17.addWidget(self.line_2)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.label_16 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_8.addWidget(self.label_16)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.verticalLayout_15.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_45 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_45.setFont(font)
        self.label_45.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.verticalLayout_4.addWidget(self.label_45)
        spacerItem12 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        self.lbl_day_1_icon = weatherIcon(Form)
        self.lbl_day_1_icon.setMinimumSize(QtCore.QSize(56, 46))
        self.lbl_day_1_icon.setMaximumSize(QtCore.QSize(71, 61))
        self.lbl_day_1_icon.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_day_1_icon.setText(_fromUtf8(""))
        self.lbl_day_1_icon.setPixmap(QtGui.QPixmap(_fromUtf8("../../res/weather/icon/NA/na.png")))
        self.lbl_day_1_icon.setScaledContents(False)
        self.lbl_day_1_icon.setObjectName(_fromUtf8("lbl_day_1_icon"))
        self.horizontalLayout_14.addWidget(self.lbl_day_1_icon)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_48 = QtGui.QLabel(Form)
        self.label_48.setMinimumSize(QtCore.QSize(8, 21))
        self.label_48.setMaximumSize(QtCore.QSize(8, 21))
        self.label_48.setText(_fromUtf8(""))
        self.label_48.setPixmap(QtGui.QPixmap(_fromUtf8(":/thermometer.png")))
        self.label_48.setScaledContents(True)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.horizontalLayout_18.addWidget(self.label_48)
        self.lbl_day_1_temp = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_day_1_temp.setFont(font)
        self.lbl_day_1_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_day_1_temp.setObjectName(_fromUtf8("lbl_day_1_temp"))
        self.horizontalLayout_18.addWidget(self.lbl_day_1_temp)
        self.label_36 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_18.addWidget(self.label_36)
        self.label_46 = QtGui.QLabel(Form)
        self.label_46.setMinimumSize(QtCore.QSize(18, 18))
        self.label_46.setMaximumSize(QtCore.QSize(18, 18))
        self.label_46.setText(_fromUtf8(""))
        self.label_46.setPixmap(QtGui.QPixmap(_fromUtf8(":/umbrella.png")))
        self.label_46.setScaledContents(True)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_18.addWidget(self.label_46)
        self.lbl_day_1_rain = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_day_1_rain.setFont(font)
        self.lbl_day_1_rain.setObjectName(_fromUtf8("lbl_day_1_rain"))
        self.horizontalLayout_18.addWidget(self.lbl_day_1_rain)
        self.label_44 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_18.addWidget(self.label_44)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_23.addLayout(self.verticalLayout_10)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem13)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_41 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_41.setFont(font)
        self.label_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.verticalLayout_5.addWidget(self.label_41)
        spacerItem14 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.lbl_night_1_icon = weatherIcon(Form)
        self.lbl_night_1_icon.setMinimumSize(QtCore.QSize(56, 46))
        self.lbl_night_1_icon.setMaximumSize(QtCore.QSize(71, 61))
        self.lbl_night_1_icon.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_night_1_icon.setText(_fromUtf8(""))
        self.lbl_night_1_icon.setPixmap(QtGui.QPixmap(_fromUtf8("../../res/weather/icon/NA/na.png")))
        self.lbl_night_1_icon.setScaledContents(False)
        self.lbl_night_1_icon.setObjectName(_fromUtf8("lbl_night_1_icon"))
        self.horizontalLayout_15.addWidget(self.lbl_night_1_icon)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_34 = QtGui.QLabel(Form)
        self.label_34.setMinimumSize(QtCore.QSize(8, 21))
        self.label_34.setMaximumSize(QtCore.QSize(8, 21))
        self.label_34.setText(_fromUtf8(""))
        self.label_34.setPixmap(QtGui.QPixmap(_fromUtf8(":/thermometer.png")))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_19.addWidget(self.label_34)
        self.lbl_night_1_temp = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_night_1_temp.setFont(font)
        self.lbl_night_1_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_night_1_temp.setObjectName(_fromUtf8("lbl_night_1_temp"))
        self.horizontalLayout_19.addWidget(self.lbl_night_1_temp)
        self.label_40 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_19.addWidget(self.label_40)
        self.label_49 = QtGui.QLabel(Form)
        self.label_49.setMinimumSize(QtCore.QSize(18, 18))
        self.label_49.setMaximumSize(QtCore.QSize(18, 18))
        self.label_49.setText(_fromUtf8(""))
        self.label_49.setPixmap(QtGui.QPixmap(_fromUtf8(":/umbrella.png")))
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_19.addWidget(self.label_49)
        self.lbl_night_1_rain = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_night_1_rain.setFont(font)
        self.lbl_night_1_rain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_night_1_rain.setObjectName(_fromUtf8("lbl_night_1_rain"))
        self.horizontalLayout_19.addWidget(self.lbl_night_1_rain)
        self.label_47 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_19.addWidget(self.label_47)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_23.addLayout(self.verticalLayout_11)
        self.verticalLayout_15.addLayout(self.horizontalLayout_23)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_17.addWidget(self.line_3)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.label_17 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_9.addWidget(self.label_17)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_56 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_56.setFont(font)
        self.label_56.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_56.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.verticalLayout_2.addWidget(self.label_56)
        spacerItem17 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem17)
        self.horizontalLayout_16.addLayout(self.verticalLayout_2)
        self.lbl_day_2_icon = weatherIcon(Form)
        self.lbl_day_2_icon.setMinimumSize(QtCore.QSize(56, 46))
        self.lbl_day_2_icon.setMaximumSize(QtCore.QSize(71, 61))
        self.lbl_day_2_icon.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_day_2_icon.setText(_fromUtf8(""))
        self.lbl_day_2_icon.setPixmap(QtGui.QPixmap(_fromUtf8("../../res/weather/icon/NA/na.png")))
        self.lbl_day_2_icon.setScaledContents(False)
        self.lbl_day_2_icon.setObjectName(_fromUtf8("lbl_day_2_icon"))
        self.horizontalLayout_16.addWidget(self.lbl_day_2_icon)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_59 = QtGui.QLabel(Form)
        self.label_59.setMinimumSize(QtCore.QSize(8, 21))
        self.label_59.setMaximumSize(QtCore.QSize(8, 21))
        self.label_59.setText(_fromUtf8(""))
        self.label_59.setPixmap(QtGui.QPixmap(_fromUtf8(":/thermometer.png")))
        self.label_59.setScaledContents(True)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.horizontalLayout_20.addWidget(self.label_59)
        self.lbl_day_2_temp = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_day_2_temp.setFont(font)
        self.lbl_day_2_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_day_2_temp.setObjectName(_fromUtf8("lbl_day_2_temp"))
        self.horizontalLayout_20.addWidget(self.lbl_day_2_temp)
        self.label_54 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.horizontalLayout_20.addWidget(self.label_54)
        self.label_57 = QtGui.QLabel(Form)
        self.label_57.setMinimumSize(QtCore.QSize(18, 18))
        self.label_57.setMaximumSize(QtCore.QSize(18, 18))
        self.label_57.setText(_fromUtf8(""))
        self.label_57.setPixmap(QtGui.QPixmap(_fromUtf8(":/umbrella.png")))
        self.label_57.setScaledContents(True)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.horizontalLayout_20.addWidget(self.label_57)
        self.lbl_day_2_rain = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_day_2_rain.setFont(font)
        self.lbl_day_2_rain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_day_2_rain.setObjectName(_fromUtf8("lbl_day_2_rain"))
        self.horizontalLayout_20.addWidget(self.lbl_day_2_rain)
        self.label_64 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_64.setFont(font)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.horizontalLayout_20.addWidget(self.label_64)
        self.verticalLayout_12.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_24.addLayout(self.verticalLayout_12)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem18)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_60 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_60.setFont(font)
        self.label_60.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_60.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.verticalLayout_3.addWidget(self.label_60)
        spacerItem19 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem19)
        self.horizontalLayout_17.addLayout(self.verticalLayout_3)
        self.lbl_night_2_icon = weatherIcon(Form)
        self.lbl_night_2_icon.setMinimumSize(QtCore.QSize(56, 46))
        self.lbl_night_2_icon.setMaximumSize(QtCore.QSize(71, 61))
        self.lbl_night_2_icon.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_night_2_icon.setText(_fromUtf8(""))
        self.lbl_night_2_icon.setPixmap(QtGui.QPixmap(_fromUtf8("../../res/weather/icon/NA/na.png")))
        self.lbl_night_2_icon.setScaledContents(False)
        self.lbl_night_2_icon.setObjectName(_fromUtf8("lbl_night_2_icon"))
        self.horizontalLayout_17.addWidget(self.lbl_night_2_icon)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_50 = QtGui.QLabel(Form)
        self.label_50.setMinimumSize(QtCore.QSize(8, 21))
        self.label_50.setMaximumSize(QtCore.QSize(8, 21))
        self.label_50.setText(_fromUtf8(""))
        self.label_50.setPixmap(QtGui.QPixmap(_fromUtf8(":/thermometer.png")))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_21.addWidget(self.label_50)
        self.lbl_night_2_temp = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_night_2_temp.setFont(font)
        self.lbl_night_2_temp.setObjectName(_fromUtf8("lbl_night_2_temp"))
        self.horizontalLayout_21.addWidget(self.lbl_night_2_temp)
        self.label_63 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.horizontalLayout_21.addWidget(self.label_63)
        self.label_61 = QtGui.QLabel(Form)
        self.label_61.setMinimumSize(QtCore.QSize(18, 18))
        self.label_61.setMaximumSize(QtCore.QSize(18, 18))
        self.label_61.setText(_fromUtf8(""))
        self.label_61.setPixmap(QtGui.QPixmap(_fromUtf8(":/umbrella.png")))
        self.label_61.setScaledContents(True)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.horizontalLayout_21.addWidget(self.label_61)
        self.lbl_night_2_rain = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lbl_night_2_rain.setFont(font)
        self.lbl_night_2_rain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_night_2_rain.setObjectName(_fromUtf8("lbl_night_2_rain"))
        self.horizontalLayout_21.addWidget(self.lbl_night_2_rain)
        self.label_65 = Scaling_QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_65.setFont(font)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.horizontalLayout_21.addWidget(self.label_65)
        self.verticalLayout_13.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_24.addLayout(self.verticalLayout_13)
        self.verticalLayout_14.addLayout(self.horizontalLayout_24)
        self.verticalLayout_17.addLayout(self.verticalLayout_14)
        self.horizontalLayout_25.addLayout(self.verticalLayout_17)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_25)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label_2.setText(_translate("Form", "Current:", None))
        self.lbl_cur_temp.setText(_translate("Form", "16", None))
        self.label_7.setText(_translate("Form", "°C , feels like", None))
        self.lbl_cur_temp_feel.setText(_translate("Form", "16", None))
        self.label_9.setText(_translate("Form", "°C ", None))
        self.lbl_cur_rain.setText(_translate("Form", "23", None))
        self.label_11.setText(_translate("Form", "% Rain probability", None))
        self.lbl_cur_wind.setText(_translate("Form", "55", None))
        self.label_13.setText(_translate("Form", "km/h Wind from", None))
        self.lbl_cur_wind_direction.setText(_translate("Form", "\"S\"", None))
        self.lbl_cur_sunrise.setText(_translate("Form", "7:22", None))
        self.lbl_cur_sunset.setText(_translate("Form", "21:55", None))
        self.label_15.setText(_translate("Form", "Monday", None))
        self.label_19.setText(_translate("Form", "Day", None))
        self.lbl_day_0_temp.setText(_translate("Form", "12", None))
        self.label_30.setText(_translate("Form", "°C ", None))
        self.lbl_day_0_rain.setText(_translate("Form", "12", None))
        self.label_31.setText(_translate("Form", "%", None))
        self.label_20.setText(_translate("Form", "Night", None))
        self.lbl_night_0_temp.setText(_translate("Form", "12", None))
        self.label_32.setText(_translate("Form", "°C ", None))
        self.lbl_night_0_rain.setText(_translate("Form", "12", None))
        self.label_33.setText(_translate("Form", "%", None))
        self.label_16.setText(_translate("Form", "Tuesday", None))
        self.label_45.setText(_translate("Form", "Day", None))
        self.lbl_day_1_temp.setText(_translate("Form", "12", None))
        self.label_36.setText(_translate("Form", "°C ", None))
        self.lbl_day_1_rain.setText(_translate("Form", "12", None))
        self.label_44.setText(_translate("Form", "%", None))
        self.label_41.setText(_translate("Form", "Night", None))
        self.lbl_night_1_temp.setText(_translate("Form", "12", None))
        self.label_40.setText(_translate("Form", "°C ", None))
        self.lbl_night_1_rain.setText(_translate("Form", "12", None))
        self.label_47.setText(_translate("Form", "%", None))
        self.label_17.setText(_translate("Form", "Wednesday", None))
        self.label_56.setText(_translate("Form", "Day", None))
        self.lbl_day_2_temp.setText(_translate("Form", "12", None))
        self.label_54.setText(_translate("Form", "°C ", None))
        self.lbl_day_2_rain.setText(_translate("Form", "12", None))
        self.label_64.setText(_translate("Form", "%", None))
        self.label_60.setText(_translate("Form", "Night", None))
        self.lbl_night_2_temp.setText(_translate("Form", "12", None))
        self.label_63.setText(_translate("Form", "°C ", None))
        self.lbl_night_2_rain.setText(_translate("Form", "12", None))
        self.label_65.setText(_translate("Form", "%", None))

from lib.LM_Widgets_scaled_contents import Scaling_QLabel
from weatherIcon import weatherIcon
