# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flexi1.ui'
#
# Created: Thu Jul 21 21:25:07 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1024, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 600))
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbl_Uhr = QtGui.QLabel(self.centralwidget)
        self.lbl_Uhr.setMinimumSize(QtCore.QSize(111, 41))
        self.lbl_Uhr.setMaximumSize(QtCore.QSize(120, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lbl_Uhr.setFont(font)
        self.lbl_Uhr.setObjectName(_fromUtf8("lbl_Uhr"))
        self.horizontalLayout_4.addWidget(self.lbl_Uhr)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(181, 41))
        self.label_2.setMaximumSize(QtCore.QSize(181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lbl_Ueberschrift = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.lbl_Ueberschrift.setFont(font)
        self.lbl_Ueberschrift.setObjectName(_fromUtf8("lbl_Ueberschrift"))
        self.horizontalLayout_4.addWidget(self.lbl_Ueberschrift)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tabWidget_main = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_main.sizePolicy().hasHeightForWidth())
        self.tabWidget_main.setSizePolicy(sizePolicy)
        self.tabWidget_main.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget_main.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget_main.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_main.setObjectName(_fromUtf8("tabWidget_main"))
        self.tabWidget_mainPage1 = QtGui.QWidget()
        self.tabWidget_mainPage1.setObjectName(_fromUtf8("tabWidget_mainPage1"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tabWidget_mainPage1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.stackedWidget = QtGui.QStackedWidget(self.tabWidget_mainPage1)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.home = QtGui.QWidget()
        self.home.setObjectName(_fromUtf8("home"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.home)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.frame = QtGui.QFrame(self.home)
        self.frame.setMinimumSize(QtCore.QSize(219, 0))
        self.frame.setMaximumSize(QtCore.QSize(219, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.lbl_Senderlogo = QtGui.QLabel(self.frame)
        self.lbl_Senderlogo.setGeometry(QtCore.QRect(0, 70, 181, 201))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Senderlogo.sizePolicy().hasHeightForWidth())
        self.lbl_Senderlogo.setSizePolicy(sizePolicy)
        self.lbl_Senderlogo.setMinimumSize(QtCore.QSize(181, 201))
        self.lbl_Senderlogo.setMaximumSize(QtCore.QSize(181, 201))
        self.lbl_Senderlogo.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_Senderlogo.setFrameShadow(QtGui.QFrame.Raised)
        self.lbl_Senderlogo.setLineWidth(2)
        self.lbl_Senderlogo.setScaledContents(True)
        self.lbl_Senderlogo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Senderlogo.setObjectName(_fromUtf8("lbl_Senderlogo"))
        self.lbl_Fav = QtGui.QLabel(self.frame)
        self.lbl_Fav.setGeometry(QtCore.QRect(150, 50, 61, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Fav.sizePolicy().hasHeightForWidth())
        self.lbl_Fav.setSizePolicy(sizePolicy)
        self.lbl_Fav.setMinimumSize(QtCore.QSize(61, 51))
        self.lbl_Fav.setMaximumSize(QtCore.QSize(61, 51))
        self.lbl_Fav.setScaledContents(True)
        self.lbl_Fav.setObjectName(_fromUtf8("lbl_Fav"))
        self.horizontalLayout_8.addWidget(self.frame)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.lbl_Sendername = Scaling_QLabel(self.home)
        self.lbl_Sendername.setMinimumSize(QtCore.QSize(0, 81))
        font = QtGui.QFont()
        font.setPointSize(55)
        self.lbl_Sendername.setFont(font)
        self.lbl_Sendername.setTextFormat(QtCore.Qt.AutoText)
        self.lbl_Sendername.setScaledContents(False)
        self.lbl_Sendername.setWordWrap(True)
        self.lbl_Sendername.setObjectName(_fromUtf8("lbl_Sendername"))
        self.verticalLayout_3.addWidget(self.lbl_Sendername)
        spacerItem1 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.label = Scaling_QLabel(self.home)
        self.label.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        spacerItem2 = QtGui.QSpacerItem(20, 3, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.lbl_Musiktitel = Scaling_QLabel(self.home)
        self.lbl_Musiktitel.setMinimumSize(QtCore.QSize(0, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lbl_Musiktitel.setFont(font)
        self.lbl_Musiktitel.setWordWrap(True)
        self.lbl_Musiktitel.setObjectName(_fromUtf8("lbl_Musiktitel"))
        self.verticalLayout_3.addWidget(self.lbl_Musiktitel)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.stackedWidget.addWidget(self.home)
        self.search_main = QtGui.QWidget()
        self.search_main.setObjectName(_fromUtf8("search_main"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.search_main)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.pB_in_ihrer_naehe = Scaling_QPushButton_Text(self.search_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_in_ihrer_naehe.sizePolicy().hasHeightForWidth())
        self.pB_in_ihrer_naehe.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pB_in_ihrer_naehe.setFont(font)
        self.pB_in_ihrer_naehe.setFlat(False)
        self.pB_in_ihrer_naehe.setObjectName(_fromUtf8("pB_in_ihrer_naehe"))
        self.verticalLayout_5.addWidget(self.pB_in_ihrer_naehe)
        spacerItem5 = QtGui.QSpacerItem(9, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem5)
        self.pB_Sendervorschlaege_fuer_sie = Scaling_QPushButton_Text(self.search_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Sendervorschlaege_fuer_sie.sizePolicy().hasHeightForWidth())
        self.pB_Sendervorschlaege_fuer_sie.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pB_Sendervorschlaege_fuer_sie.setFont(font)
        self.pB_Sendervorschlaege_fuer_sie.setObjectName(_fromUtf8("pB_Sendervorschlaege_fuer_sie"))
        self.verticalLayout_5.addWidget(self.pB_Sendervorschlaege_fuer_sie)
        spacerItem6 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem6)
        self.pB_sender_nach_kategorie = Scaling_QPushButton_Text(self.search_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_sender_nach_kategorie.sizePolicy().hasHeightForWidth())
        self.pB_sender_nach_kategorie.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pB_sender_nach_kategorie.setFont(font)
        self.pB_sender_nach_kategorie.setObjectName(_fromUtf8("pB_sender_nach_kategorie"))
        self.verticalLayout_5.addWidget(self.pB_sender_nach_kategorie)
        spacerItem7 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem7)
        self.pB_sender_suchen = Scaling_QPushButton_Text(self.search_main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_sender_suchen.sizePolicy().hasHeightForWidth())
        self.pB_sender_suchen.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pB_sender_suchen.setFont(font)
        self.pB_sender_suchen.setObjectName(_fromUtf8("pB_sender_suchen"))
        self.verticalLayout_5.addWidget(self.pB_sender_suchen)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.stackedWidget.addWidget(self.search_main)
        self.result_nearyou = QtGui.QWidget()
        self.result_nearyou.setObjectName(_fromUtf8("result_nearyou"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.result_nearyou)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.lW_in_ihrer_naehe = QtGui.QListWidget(self.result_nearyou)
        self.lW_in_ihrer_naehe.setObjectName(_fromUtf8("lW_in_ihrer_naehe"))
        self.horizontalLayout_9.addWidget(self.lW_in_ihrer_naehe)
        self.stackedWidget.addWidget(self.result_nearyou)
        self.result_suggestions = QtGui.QWidget()
        self.result_suggestions.setObjectName(_fromUtf8("result_suggestions"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.result_suggestions)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lW_sendervorschlaege = QtGui.QListWidget(self.result_suggestions)
        self.lW_sendervorschlaege.setObjectName(_fromUtf8("lW_sendervorschlaege"))
        self.verticalLayout_9.addWidget(self.lW_sendervorschlaege)
        self.stackedWidget.addWidget(self.result_suggestions)
        self.search_by_categorie = QtGui.QWidget()
        self.search_by_categorie.setObjectName(_fromUtf8("search_by_categorie"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.search_by_categorie)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem9 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem9)
        self.pB_nach_Genre = Scaling_QPushButton_Text(self.search_by_categorie)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_nach_Genre.sizePolicy().hasHeightForWidth())
        self.pB_nach_Genre.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pB_nach_Genre.setFont(font)
        self.pB_nach_Genre.setObjectName(_fromUtf8("pB_nach_Genre"))
        self.verticalLayout_7.addWidget(self.pB_nach_Genre)
        self.pB_nach_Thema = Scaling_QPushButton_Text(self.search_by_categorie)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_nach_Thema.sizePolicy().hasHeightForWidth())
        self.pB_nach_Thema.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pB_nach_Thema.setFont(font)
        self.pB_nach_Thema.setObjectName(_fromUtf8("pB_nach_Thema"))
        self.verticalLayout_7.addWidget(self.pB_nach_Thema)
        self.pB_nach_Land = Scaling_QPushButton_Text(self.search_by_categorie)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_nach_Land.sizePolicy().hasHeightForWidth())
        self.pB_nach_Land.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pB_nach_Land.setFont(font)
        self.pB_nach_Land.setObjectName(_fromUtf8("pB_nach_Land"))
        self.verticalLayout_7.addWidget(self.pB_nach_Land)
        self.pB_nach_Stadt = Scaling_QPushButton_Text(self.search_by_categorie)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_nach_Stadt.sizePolicy().hasHeightForWidth())
        self.pB_nach_Stadt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pB_nach_Stadt.setFont(font)
        self.pB_nach_Stadt.setObjectName(_fromUtf8("pB_nach_Stadt"))
        self.verticalLayout_7.addWidget(self.pB_nach_Stadt)
        self.pB_nach_Sprache = Scaling_QPushButton_Text(self.search_by_categorie)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_nach_Sprache.sizePolicy().hasHeightForWidth())
        self.pB_nach_Sprache.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pB_nach_Sprache.setFont(font)
        self.pB_nach_Sprache.setObjectName(_fromUtf8("pB_nach_Sprache"))
        self.verticalLayout_7.addWidget(self.pB_nach_Sprache)
        spacerItem10 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem10)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.stackedWidget.addWidget(self.search_by_categorie)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.lW_kategorievorschlaege = QtGui.QListWidget(self.page)
        self.lW_kategorievorschlaege.setObjectName(_fromUtf8("lW_kategorievorschlaege"))
        self.verticalLayout_10.addWidget(self.lW_kategorievorschlaege)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.page_2)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lW_stationen_nach_cat = QtGui.QListWidget(self.page_2)
        self.lW_stationen_nach_cat.setObjectName(_fromUtf8("lW_stationen_nach_cat"))
        self.horizontalLayout_10.addWidget(self.lW_stationen_nach_cat)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.tabWidget_main.addTab(self.tabWidget_mainPage1, _fromUtf8(""))
        self.tabWidget_mainPage2 = QtGui.QWidget()
        self.tabWidget_mainPage2.setObjectName(_fromUtf8("tabWidget_mainPage2"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.tabWidget_mainPage2)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.stackedWidget_2 = QtGui.QStackedWidget(self.tabWidget_mainPage2)
        self.stackedWidget_2.setObjectName(_fromUtf8("stackedWidget_2"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.page_5)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.treeView = LM_QTreeView(self.page_5)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.treeView.setFont(font)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout_14.addWidget(self.treeView)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.pB_relead_tree = QtGui.QPushButton(self.page_5)
        self.pB_relead_tree.setMinimumSize(QtCore.QSize(0, 51))
        self.pB_relead_tree.setObjectName(_fromUtf8("pB_relead_tree"))
        self.horizontalLayout_21.addWidget(self.pB_relead_tree)
        self.pB_add_to_playlist = QtGui.QPushButton(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_add_to_playlist.sizePolicy().hasHeightForWidth())
        self.pB_add_to_playlist.setSizePolicy(sizePolicy)
        self.pB_add_to_playlist.setMinimumSize(QtCore.QSize(0, 51))
        self.pB_add_to_playlist.setObjectName(_fromUtf8("pB_add_to_playlist"))
        self.horizontalLayout_21.addWidget(self.pB_add_to_playlist)
        self.verticalLayout_14.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22.addLayout(self.verticalLayout_14)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.page_6)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.frame_2 = QtGui.QFrame(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(254, 241))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 304))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.lbl_albumArt = QtGui.QLabel(self.frame_2)
        self.lbl_albumArt.setGeometry(QtCore.QRect(10, 10, 211, 241))
        self.lbl_albumArt.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_albumArt.setObjectName(_fromUtf8("lbl_albumArt"))
        self.horizontalLayout_15.addWidget(self.frame_2)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem11)
        self.lbl_previouse = Scaling_QLabel(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_previouse.sizePolicy().hasHeightForWidth())
        self.lbl_previouse.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_previouse.setFont(font)
        self.lbl_previouse.setStyleSheet(_fromUtf8("QLabel { color: rgba(0, 0, 0, 50%) }"))
        self.lbl_previouse.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_previouse.setObjectName(_fromUtf8("lbl_previouse"))
        self.verticalLayout_11.addWidget(self.lbl_previouse)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem12 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.lbl_current_playing = Scaling_QLabel(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_current_playing.sizePolicy().hasHeightForWidth())
        self.lbl_current_playing.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_current_playing.setFont(font)
        self.lbl_current_playing.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_current_playing.setObjectName(_fromUtf8("lbl_current_playing"))
        self.horizontalLayout_14.addWidget(self.lbl_current_playing)
        spacerItem13 = QtGui.QSpacerItem(24, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.lbl_next = Scaling_QLabel(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_next.sizePolicy().hasHeightForWidth())
        self.lbl_next.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lbl_next.setFont(font)
        self.lbl_next.setStyleSheet(_fromUtf8("QLabel { color: rgba(0, 0, 0, 50%) }"))
        self.lbl_next.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_next.setObjectName(_fromUtf8("lbl_next"))
        self.verticalLayout_11.addWidget(self.lbl_next)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem14)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.lbl_current_seek = QtGui.QLabel(self.page_6)
        self.lbl_current_seek.setObjectName(_fromUtf8("lbl_current_seek"))
        self.horizontalLayout_12.addWidget(self.lbl_current_seek)
        self.slide_seek = QtGui.QSlider(self.page_6)
        self.slide_seek.setMinimumSize(QtCore.QSize(361, 29))
        self.slide_seek.setOrientation(QtCore.Qt.Horizontal)
        self.slide_seek.setObjectName(_fromUtf8("slide_seek"))
        self.horizontalLayout_12.addWidget(self.slide_seek)
        self.lbl_total_seek = QtGui.QLabel(self.page_6)
        self.lbl_total_seek.setObjectName(_fromUtf8("lbl_total_seek"))
        self.horizontalLayout_12.addWidget(self.lbl_total_seek)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem16)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(17)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.pB_autorepeat_2 = QtGui.QPushButton(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_autorepeat_2.sizePolicy().hasHeightForWidth())
        self.pB_autorepeat_2.setSizePolicy(sizePolicy)
        self.pB_autorepeat_2.setMinimumSize(QtCore.QSize(81, 51))
        self.pB_autorepeat_2.setMaximumSize(QtCore.QSize(16777215, 61))
        self.pB_autorepeat_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pB_autorepeat_2.setCheckable(True)
        self.pB_autorepeat_2.setObjectName(_fromUtf8("pB_autorepeat_2"))
        self.horizontalLayout_11.addWidget(self.pB_autorepeat_2)
        self.pB_Audio_back = QtGui.QPushButton(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Audio_back.sizePolicy().hasHeightForWidth())
        self.pB_Audio_back.setSizePolicy(sizePolicy)
        self.pB_Audio_back.setMinimumSize(QtCore.QSize(80, 51))
        self.pB_Audio_back.setMaximumSize(QtCore.QSize(111, 61))
        self.pB_Audio_back.setObjectName(_fromUtf8("pB_Audio_back"))
        self.horizontalLayout_11.addWidget(self.pB_Audio_back)
        self.pB_Audio_stop = QtGui.QPushButton(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Audio_stop.sizePolicy().hasHeightForWidth())
        self.pB_Audio_stop.setSizePolicy(sizePolicy)
        self.pB_Audio_stop.setMinimumSize(QtCore.QSize(90, 51))
        self.pB_Audio_stop.setMaximumSize(QtCore.QSize(151, 61))
        self.pB_Audio_stop.setObjectName(_fromUtf8("pB_Audio_stop"))
        self.horizontalLayout_11.addWidget(self.pB_Audio_stop)
        self.pB_Audio_play_pause = QtGui.QPushButton(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Audio_play_pause.sizePolicy().hasHeightForWidth())
        self.pB_Audio_play_pause.setSizePolicy(sizePolicy)
        self.pB_Audio_play_pause.setMinimumSize(QtCore.QSize(90, 51))
        self.pB_Audio_play_pause.setMaximumSize(QtCore.QSize(151, 61))
        self.pB_Audio_play_pause.setObjectName(_fromUtf8("pB_Audio_play_pause"))
        self.horizontalLayout_11.addWidget(self.pB_Audio_play_pause)
        self.pB_Audio_forward = QtGui.QPushButton(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Audio_forward.sizePolicy().hasHeightForWidth())
        self.pB_Audio_forward.setSizePolicy(sizePolicy)
        self.pB_Audio_forward.setMinimumSize(QtCore.QSize(80, 51))
        self.pB_Audio_forward.setMaximumSize(QtCore.QSize(111, 61))
        self.pB_Audio_forward.setObjectName(_fromUtf8("pB_Audio_forward"))
        self.horizontalLayout_11.addWidget(self.pB_Audio_forward)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_16.addLayout(self.verticalLayout_12)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.page_3)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.listWidget = QtGui.QListWidget(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_16.addWidget(self.listWidget)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.pB_autorepeat = QtGui.QPushButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_autorepeat.sizePolicy().hasHeightForWidth())
        self.pB_autorepeat.setSizePolicy(sizePolicy)
        self.pB_autorepeat.setMinimumSize(QtCore.QSize(65, 51))
        self.pB_autorepeat.setMaximumSize(QtCore.QSize(81, 61))
        self.pB_autorepeat.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pB_autorepeat.setCheckable(True)
        self.pB_autorepeat.setObjectName(_fromUtf8("pB_autorepeat"))
        self.horizontalLayout_13.addWidget(self.pB_autorepeat)
        self.pB_Audio_back_2 = QtGui.QPushButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Audio_back_2.sizePolicy().hasHeightForWidth())
        self.pB_Audio_back_2.setSizePolicy(sizePolicy)
        self.pB_Audio_back_2.setMinimumSize(QtCore.QSize(65, 51))
        self.pB_Audio_back_2.setMaximumSize(QtCore.QSize(81, 61))
        self.pB_Audio_back_2.setObjectName(_fromUtf8("pB_Audio_back_2"))
        self.horizontalLayout_13.addWidget(self.pB_Audio_back_2)
        self.pB_Audio_stop_2 = QtGui.QPushButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Audio_stop_2.sizePolicy().hasHeightForWidth())
        self.pB_Audio_stop_2.setSizePolicy(sizePolicy)
        self.pB_Audio_stop_2.setMinimumSize(QtCore.QSize(65, 51))
        self.pB_Audio_stop_2.setMaximumSize(QtCore.QSize(121, 61))
        self.pB_Audio_stop_2.setObjectName(_fromUtf8("pB_Audio_stop_2"))
        self.horizontalLayout_13.addWidget(self.pB_Audio_stop_2)
        self.pB_Audio_play_pause_2 = QtGui.QPushButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Audio_play_pause_2.sizePolicy().hasHeightForWidth())
        self.pB_Audio_play_pause_2.setSizePolicy(sizePolicy)
        self.pB_Audio_play_pause_2.setMinimumSize(QtCore.QSize(65, 51))
        self.pB_Audio_play_pause_2.setMaximumSize(QtCore.QSize(121, 61))
        self.pB_Audio_play_pause_2.setObjectName(_fromUtf8("pB_Audio_play_pause_2"))
        self.horizontalLayout_13.addWidget(self.pB_Audio_play_pause_2)
        self.pB_Audio_forward_2 = QtGui.QPushButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pB_Audio_forward_2.sizePolicy().hasHeightForWidth())
        self.pB_Audio_forward_2.setSizePolicy(sizePolicy)
        self.pB_Audio_forward_2.setMinimumSize(QtCore.QSize(65, 51))
        self.pB_Audio_forward_2.setMaximumSize(QtCore.QSize(81, 61))
        self.pB_Audio_forward_2.setObjectName(_fromUtf8("pB_Audio_forward_2"))
        self.horizontalLayout_13.addWidget(self.pB_Audio_forward_2)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem20)
        self.verticalLayout_16.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_17.addLayout(self.verticalLayout_16)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem21)
        self.pB_move_down_2 = QtGui.QPushButton(self.page_3)
        self.pB_move_down_2.setMinimumSize(QtCore.QSize(61, 61))
        self.pB_move_down_2.setMaximumSize(QtCore.QSize(61, 91))
        self.pB_move_down_2.setObjectName(_fromUtf8("pB_move_down_2"))
        self.verticalLayout_15.addWidget(self.pB_move_down_2)
        self.pB_add_on_playlist = QtGui.QPushButton(self.page_3)
        self.pB_add_on_playlist.setMinimumSize(QtCore.QSize(61, 51))
        self.pB_add_on_playlist.setMaximumSize(QtCore.QSize(61, 16777215))
        self.pB_add_on_playlist.setObjectName(_fromUtf8("pB_add_on_playlist"))
        self.verticalLayout_15.addWidget(self.pB_add_on_playlist)
        self.pB_del_from_playlist = QtGui.QPushButton(self.page_3)
        self.pB_del_from_playlist.setMinimumSize(QtCore.QSize(61, 51))
        self.pB_del_from_playlist.setMaximumSize(QtCore.QSize(61, 16777215))
        self.pB_del_from_playlist.setObjectName(_fromUtf8("pB_del_from_playlist"))
        self.verticalLayout_15.addWidget(self.pB_del_from_playlist)
        self.pB_move_down = QtGui.QPushButton(self.page_3)
        self.pB_move_down.setMinimumSize(QtCore.QSize(61, 61))
        self.pB_move_down.setMaximumSize(QtCore.QSize(61, 91))
        self.pB_move_down.setObjectName(_fromUtf8("pB_move_down"))
        self.verticalLayout_15.addWidget(self.pB_move_down)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem22)
        self.pB_markAll = QtGui.QPushButton(self.page_3)
        self.pB_markAll.setMinimumSize(QtCore.QSize(81, 61))
        self.pB_markAll.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pB_markAll.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pB_markAll.setObjectName(_fromUtf8("pB_markAll"))
        self.verticalLayout_15.addWidget(self.pB_markAll)
        self.horizontalLayout_17.addLayout(self.verticalLayout_15)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        self.stackedWidget_2.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.page_4)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.treeWidget_2 = LM_QTreeWidget(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.treeWidget_2.setFont(font)
        self.treeWidget_2.setObjectName(_fromUtf8("treeWidget_2"))
        self.treeWidget_2.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_13.addWidget(self.treeWidget_2)
        self.pB_add_to_playlist_2 = QtGui.QPushButton(self.page_4)
        self.pB_add_to_playlist_2.setMinimumSize(QtCore.QSize(0, 51))
        self.pB_add_to_playlist_2.setObjectName(_fromUtf8("pB_add_to_playlist_2"))
        self.verticalLayout_13.addWidget(self.pB_add_to_playlist_2)
        self.horizontalLayout_20.addLayout(self.verticalLayout_13)
        self.stackedWidget_2.addWidget(self.page_4)
        self.horizontalLayout_19.addWidget(self.stackedWidget_2)
        self.tabWidget_main.addTab(self.tabWidget_mainPage2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget_main.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        spacerItem23 = QtGui.QSpacerItem(16, 26, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_17.addItem(spacerItem23)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem24)
        self.widget_sleep_timer = SleepTimer(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_sleep_timer.sizePolicy().hasHeightForWidth())
        self.widget_sleep_timer.setSizePolicy(sizePolicy)
        self.widget_sleep_timer.setMinimumSize(QtCore.QSize(246, 346))
        self.widget_sleep_timer.setMaximumSize(QtCore.QSize(485, 366))
        self.widget_sleep_timer.setObjectName(_fromUtf8("widget_sleep_timer"))
        self.horizontalLayout_23.addWidget(self.widget_sleep_timer)
        spacerItem25 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem25)
        self.verticalLayout_17.addLayout(self.horizontalLayout_23)
        spacerItem26 = QtGui.QSpacerItem(20, 24, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_17.addItem(spacerItem26)
        self.horizontalLayout_24.addLayout(self.verticalLayout_17)
        self.tabWidget_main.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.stackedWidget_3 = QtGui.QStackedWidget(self.tab_3)
        self.stackedWidget_3.setObjectName(_fromUtf8("stackedWidget_3"))
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.label_3 = Scaling_QLabel(self.page_7)
        self.label_3.setGeometry(QtCore.QRect(70, 50, 151, 41))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cB_design = QtGui.QComboBox(self.page_7)
        self.cB_design.setGeometry(QtCore.QRect(230, 50, 211, 41))
        self.cB_design.setObjectName(_fromUtf8("cB_design"))
        self.stackedWidget_3.addWidget(self.page_7)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.stackedWidget_3.addWidget(self.page_8)
        self.horizontalLayout_25.addWidget(self.stackedWidget_3)
        self.tabWidget_main.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.tabWidget_main)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem27 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem27)
        self.pBHome = Scaling_QPushButton_Icon(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBHome.sizePolicy().hasHeightForWidth())
        self.pBHome.setSizePolicy(sizePolicy)
        self.pBHome.setMaximumSize(QtCore.QSize(91, 94))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pBHome.setFont(font)
        self.pBHome.setObjectName(_fromUtf8("pBHome"))
        self.verticalLayout.addWidget(self.pBHome)
        spacerItem28 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem28)
        self.pBSuchen = Scaling_QPushButton_Icon(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBSuchen.sizePolicy().hasHeightForWidth())
        self.pBSuchen.setSizePolicy(sizePolicy)
        self.pBSuchen.setMaximumSize(QtCore.QSize(94, 91))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pBSuchen.setFont(font)
        self.pBSuchen.setObjectName(_fromUtf8("pBSuchen"))
        self.verticalLayout.addWidget(self.pBSuchen)
        spacerItem29 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem29)
        self.pBFavoriten = Scaling_QPushButton_Icon(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBFavoriten.sizePolicy().hasHeightForWidth())
        self.pBFavoriten.setSizePolicy(sizePolicy)
        self.pBFavoriten.setMaximumSize(QtCore.QSize(94, 91))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pBFavoriten.setFont(font)
        self.pBFavoriten.setObjectName(_fromUtf8("pBFavoriten"))
        self.verticalLayout.addWidget(self.pBFavoriten)
        spacerItem30 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem30)
        self.pBZurueck = Scaling_QPushButton_Icon(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pBZurueck.sizePolicy().hasHeightForWidth())
        self.pBZurueck.setSizePolicy(sizePolicy)
        self.pBZurueck.setMaximumSize(QtCore.QSize(94, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pBZurueck.setFont(font)
        self.pBZurueck.setObjectName(_fromUtf8("pBZurueck"))
        self.verticalLayout.addWidget(self.pBZurueck)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_Mute_1 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_Mute_1.sizePolicy().hasHeightForWidth())
        self.widget_Mute_1.setSizePolicy(sizePolicy)
        self.widget_Mute_1.setMinimumSize(QtCore.QSize(80, 80))
        self.widget_Mute_1.setMaximumSize(QtCore.QSize(80, 80))
        self.widget_Mute_1.setObjectName(_fromUtf8("widget_Mute_1"))
        self.horizontalLayout.addWidget(self.widget_Mute_1)
        self.widget_Mute_2 = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_Mute_2.sizePolicy().hasHeightForWidth())
        self.widget_Mute_2.setSizePolicy(sizePolicy)
        self.widget_Mute_2.setMinimumSize(QtCore.QSize(80, 80))
        self.widget_Mute_2.setMaximumSize(QtCore.QSize(80, 80))
        self.widget_Mute_2.setObjectName(_fromUtf8("widget_Mute_2"))
        self.horizontalLayout.addWidget(self.widget_Mute_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem31 = QtGui.QSpacerItem(76, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem31)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pBVol_down = Scaling_QPushButton_Icon(self.centralwidget)
        self.pBVol_down.setMinimumSize(QtCore.QSize(47, 47))
        self.pBVol_down.setMaximumSize(QtCore.QSize(47, 47))
        self.pBVol_down.setObjectName(_fromUtf8("pBVol_down"))
        self.horizontalLayout_2.addWidget(self.pBVol_down)
        self.slider_vol = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_vol.sizePolicy().hasHeightForWidth())
        self.slider_vol.setSizePolicy(sizePolicy)
        self.slider_vol.setMinimumSize(QtCore.QSize(256, 0))
        self.slider_vol.setOrientation(QtCore.Qt.Horizontal)
        self.slider_vol.setObjectName(_fromUtf8("slider_vol"))
        self.horizontalLayout_2.addWidget(self.slider_vol)
        self.pBVol_up = Scaling_QPushButton_Icon(self.centralwidget)
        self.pBVol_up.setMinimumSize(QtCore.QSize(47, 47))
        self.pBVol_up.setMaximumSize(QtCore.QSize(47, 47))
        self.pBVol_up.setObjectName(_fromUtf8("pBVol_up"))
        self.horizontalLayout_2.addWidget(self.pBVol_up)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem32 = QtGui.QSpacerItem(149, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem32)
        self.horizontalLayout_3.setStretch(2, 3)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(4)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(1)
        self.stackedWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Raspi Web Radio", None))
        self.lbl_Uhr.setText(_translate("MainWindow", "16:35 Uhr", None))
        self.lbl_Ueberschrift.setText(_translate("MainWindow", "Raspi - Web Radio Tuner", None))
        self.lbl_Senderlogo.setText(_translate("MainWindow", "Senderlogo", None))
        self.lbl_Fav.setText(_translate("MainWindow", "fav", None))
        self.lbl_Sendername.setText(_translate("MainWindow", "Rock Antenne", None))
        self.label.setText(_translate("MainWindow", "currently playing...", None))
        self.lbl_Musiktitel.setText(_translate("MainWindow", "Musiktitel", None))
        self.pB_in_ihrer_naehe.setText(_translate("MainWindow", "Stations near of you", None))
        self.pB_Sendervorschlaege_fuer_sie.setText(_translate("MainWindow", "Station proposals", None))
        self.pB_sender_nach_kategorie.setText(_translate("MainWindow", "Choose station by category", None))
        self.pB_sender_suchen.setText(_translate("MainWindow", "Search stations...", None))
        self.pB_nach_Genre.setText(_translate("MainWindow", "Station by \"Genre\"", None))
        self.pB_nach_Thema.setText(_translate("MainWindow", "Station by \"Theme\"", None))
        self.pB_nach_Land.setText(_translate("MainWindow", "Station by \"Country\"", None))
        self.pB_nach_Stadt.setText(_translate("MainWindow", "Station by \"Town\"", None))
        self.pB_nach_Sprache.setText(_translate("MainWindow", "Station by \"Language\"", None))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tabWidget_mainPage1), _translate("MainWindow", "Web-Radio", None))
        self.pB_relead_tree.setText(_translate("MainWindow", "reload", None))
        self.pB_add_to_playlist.setText(_translate("MainWindow", "Add to Playlist", None))
        self.lbl_albumArt.setText(_translate("MainWindow", "Album Art", None))
        self.lbl_previouse.setText(_translate("MainWindow", "Previouse Song", None))
        self.lbl_current_playing.setText(_translate("MainWindow", "Current Song", None))
        self.lbl_next.setText(_translate("MainWindow", "Next Song", None))
        self.lbl_current_seek.setText(_translate("MainWindow", "cur", None))
        self.lbl_total_seek.setText(_translate("MainWindow", "total", None))
        self.pB_autorepeat_2.setText(_translate("MainWindow", "autorepeat", None))
        self.pB_Audio_back.setText(_translate("MainWindow", "Back", None))
        self.pB_Audio_stop.setText(_translate("MainWindow", "Stop", None))
        self.pB_Audio_play_pause.setText(_translate("MainWindow", "Play", None))
        self.pB_Audio_forward.setText(_translate("MainWindow", "Forward", None))
        self.pB_autorepeat.setText(_translate("MainWindow", "autorepeat", None))
        self.pB_Audio_back_2.setText(_translate("MainWindow", "Back", None))
        self.pB_Audio_stop_2.setText(_translate("MainWindow", "Stop", None))
        self.pB_Audio_play_pause_2.setText(_translate("MainWindow", "Play", None))
        self.pB_Audio_forward_2.setText(_translate("MainWindow", "Forward", None))
        self.pB_move_down_2.setText(_translate("MainWindow", "up", None))
        self.pB_add_on_playlist.setText(_translate("MainWindow", "add", None))
        self.pB_del_from_playlist.setText(_translate("MainWindow", "del", None))
        self.pB_move_down.setText(_translate("MainWindow", "down", None))
        self.pB_markAll.setText(_translate("MainWindow", "MarkAll", None))
        self.pB_add_to_playlist_2.setText(_translate("MainWindow", "Add to Playlist", None))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tabWidget_mainPage2), _translate("MainWindow", "MP3 Player", None))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab), _translate("MainWindow", "Wetter", None))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_2), _translate("MainWindow", "Sleep-Timer", None))
        self.label_3.setText(_translate("MainWindow", "Design-Vorlage:", None))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tab_3), _translate("MainWindow", "Settings", None))
        self.pBHome.setText(_translate("MainWindow", "Home", None))
        self.pBSuchen.setText(_translate("MainWindow", "Suchen", None))
        self.pBFavoriten.setText(_translate("MainWindow", "Fav", None))
        self.pBZurueck.setText(_translate("MainWindow", "Zurück", None))
        self.pBVol_down.setText(_translate("MainWindow", "-", None))
        self.pBVol_up.setText(_translate("MainWindow", "+", None))

from mpd_filesystemView import LM_QTreeView
from database_searcher import LM_QTreeWidget
from sleeptimer import SleepTimer
from lib.LM_Widgets_scaled_contents import Scaling_QPushButton_Text, Scaling_QPushButton_Icon, Scaling_QLabel
