# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'installation_guide.ui'
#
# Created: Sun Jun 19 15:46:41 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Installation_Guide(object):
    def setupUi(self, Installation_Guide):
        Installation_Guide.setObjectName(_fromUtf8("Installation_Guide"))
        Installation_Guide.resize(1024, 600)
        Installation_Guide.setMinimumSize(QtCore.QSize(640, 480))
        Installation_Guide.setMaximumSize(QtCore.QSize(1024, 600))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(Installation_Guide)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.rB_introduction = QtGui.QRadioButton(Installation_Guide)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rB_introduction.setFont(font)
        self.rB_introduction.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rB_introduction.setCheckable(False)
        self.rB_introduction.setChecked(False)
        self.rB_introduction.setAutoExclusive(False)
        self.rB_introduction.setObjectName(_fromUtf8("rB_introduction"))
        self.verticalLayout_4.addWidget(self.rB_introduction)
        self.rB_install_dependencies = QtGui.QRadioButton(Installation_Guide)
        self.rB_install_dependencies.setEnabled(False)
        self.rB_install_dependencies.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rB_install_dependencies.setCheckable(False)
        self.rB_install_dependencies.setAutoExclusive(False)
        self.rB_install_dependencies.setObjectName(_fromUtf8("rB_install_dependencies"))
        self.verticalLayout_4.addWidget(self.rB_install_dependencies)
        self.rB_setup_mpd = QtGui.QRadioButton(Installation_Guide)
        self.rB_setup_mpd.setEnabled(False)
        self.rB_setup_mpd.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rB_setup_mpd.setCheckable(False)
        self.rB_setup_mpd.setAutoExclusive(False)
        self.rB_setup_mpd.setObjectName(_fromUtf8("rB_setup_mpd"))
        self.verticalLayout_4.addWidget(self.rB_setup_mpd)
        self.rB_setup_usb_behaviour = QtGui.QRadioButton(Installation_Guide)
        self.rB_setup_usb_behaviour.setEnabled(False)
        self.rB_setup_usb_behaviour.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rB_setup_usb_behaviour.setCheckable(False)
        self.rB_setup_usb_behaviour.setAutoExclusive(False)
        self.rB_setup_usb_behaviour.setObjectName(_fromUtf8("rB_setup_usb_behaviour"))
        self.verticalLayout_4.addWidget(self.rB_setup_usb_behaviour)
        self.rb_connect_nas = QtGui.QRadioButton(Installation_Guide)
        self.rb_connect_nas.setEnabled(False)
        self.rb_connect_nas.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rb_connect_nas.setCheckable(False)
        self.rb_connect_nas.setAutoExclusive(False)
        self.rb_connect_nas.setObjectName(_fromUtf8("rb_connect_nas"))
        self.verticalLayout_4.addWidget(self.rb_connect_nas)
        self.rb_setup_gpios = QtGui.QRadioButton(Installation_Guide)
        self.rb_setup_gpios.setEnabled(False)
        self.rb_setup_gpios.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rb_setup_gpios.setCheckable(False)
        self.rb_setup_gpios.setAutoExclusive(False)
        self.rb_setup_gpios.setObjectName(_fromUtf8("rb_setup_gpios"))
        self.verticalLayout_4.addWidget(self.rb_setup_gpios)
        self.rB_setup_webradio = QtGui.QRadioButton(Installation_Guide)
        self.rB_setup_webradio.setEnabled(False)
        self.rB_setup_webradio.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.rB_setup_webradio.setCheckable(False)
        self.rB_setup_webradio.setAutoExclusive(False)
        self.rB_setup_webradio.setObjectName(_fromUtf8("rB_setup_webradio"))
        self.verticalLayout_4.addWidget(self.rB_setup_webradio)
        spacerItem1 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.lbl_logo = Scaling_QLabel_pixmap(Installation_Guide)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_logo.sizePolicy().hasHeightForWidth())
        self.lbl_logo.setSizePolicy(sizePolicy)
        self.lbl_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_logo.setObjectName(_fromUtf8("lbl_logo"))
        self.verticalLayout_4.addWidget(self.lbl_logo)
        spacerItem2 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.line = QtGui.QFrame(Installation_Guide)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.lbl_title = QtGui.QLabel(Installation_Guide)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_title.sizePolicy().hasHeightForWidth())
        self.lbl_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lbl_title.setFont(font)
        self.lbl_title.setFrameShape(QtGui.QFrame.Panel)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName(_fromUtf8("lbl_title"))
        self.horizontalLayout_2.addWidget(self.lbl_title)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtGui.QStackedWidget(Installation_Guide)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.step1 = QtGui.QWidget()
        self.step1.setObjectName(_fromUtf8("step1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.step1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.step1)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.label_2 = QtGui.QLabel(self.step1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_3 = QtGui.QLabel(self.step1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.step1)
        self.step2 = QtGui.QWidget()
        self.step2.setObjectName(_fromUtf8("step2"))
        self.stackedWidget.addWidget(self.step2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.setStretch(2, 2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pB_abort = QtGui.QPushButton(Installation_Guide)
        self.pB_abort.setMinimumSize(QtCore.QSize(0, 45))
        self.pB_abort.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pB_abort.setObjectName(_fromUtf8("pB_abort"))
        self.horizontalLayout.addWidget(self.pB_abort)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.pB_previouse = QtGui.QPushButton(Installation_Guide)
        self.pB_previouse.setMinimumSize(QtCore.QSize(0, 45))
        self.pB_previouse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pB_previouse.setObjectName(_fromUtf8("pB_previouse"))
        self.horizontalLayout.addWidget(self.pB_previouse)
        self.pB_next = QtGui.QPushButton(Installation_Guide)
        self.pB_next.setMinimumSize(QtCore.QSize(0, 45))
        self.pB_next.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pB_next.setDefault(True)
        self.pB_next.setObjectName(_fromUtf8("pB_next"))
        self.horizontalLayout.addWidget(self.pB_next)
        spacerItem7 = QtGui.QSpacerItem(92, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.pB_finished = QtGui.QPushButton(Installation_Guide)
        self.pB_finished.setMinimumSize(QtCore.QSize(0, 45))
        self.pB_finished.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.pB_finished.setObjectName(_fromUtf8("pB_finished"))
        self.horizontalLayout.addWidget(self.pB_finished)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)

        self.retranslateUi(Installation_Guide)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Installation_Guide)
        Installation_Guide.setTabOrder(self.pB_next, self.pB_previouse)
        Installation_Guide.setTabOrder(self.pB_previouse, self.pB_finished)
        Installation_Guide.setTabOrder(self.pB_finished, self.pB_abort)
        Installation_Guide.setTabOrder(self.pB_abort, self.rB_introduction)
        Installation_Guide.setTabOrder(self.rB_introduction, self.rB_install_dependencies)
        Installation_Guide.setTabOrder(self.rB_install_dependencies, self.rB_setup_mpd)
        Installation_Guide.setTabOrder(self.rB_setup_mpd, self.rB_setup_usb_behaviour)
        Installation_Guide.setTabOrder(self.rB_setup_usb_behaviour, self.rb_connect_nas)
        Installation_Guide.setTabOrder(self.rb_connect_nas, self.rb_setup_gpios)
        Installation_Guide.setTabOrder(self.rb_setup_gpios, self.rB_setup_webradio)

    def retranslateUi(self, Installation_Guide):
        Installation_Guide.setWindowTitle(_translate("Installation_Guide", "Installation Guide", None))
        self.rB_introduction.setText(_translate("Installation_Guide", "Introduction", None))
        self.rB_install_dependencies.setText(_translate("Installation_Guide", "Install dependencies", None))
        self.rB_setup_mpd.setText(_translate("Installation_Guide", "Setup MPD", None))
        self.rB_setup_usb_behaviour.setText(_translate("Installation_Guide", "setup USB behaviour", None))
        self.rb_connect_nas.setText(_translate("Installation_Guide", "Connect NAS", None))
        self.rb_setup_gpios.setText(_translate("Installation_Guide", "Setup GPIOs", None))
        self.rB_setup_webradio.setText(_translate("Installation_Guide", "Setup webradio.py", None))
        self.lbl_logo.setText(_translate("Installation_Guide", "Logo", None))
        self.lbl_title.setText(_translate("Installation_Guide", "Title", None))
        self.label.setText(_translate("Installation_Guide", "Welcome to the guided installation of \"webradio.py\" ", None))
        self.label_2.setText(_translate("Installation_Guide", "Version: ", None))
        self.label_3.setText(_translate("Installation_Guide", "\n"
"This is the automated installation-guide for the Python-Programm \"webradio.py\" it will basically configure the file \"webradio.conf\" which is located in the folder where you have stored the installation.pack of webradio.py.\n"
"You can change your setting when ever you want just by calling this script once again. If you are sure about your needed changes you can also open the webradio.conf file with a text-editor of your choice. Just change and safe the file and restart \"webradio.py\".\n"
"\n"
"During the next few slides you will be asked for specific details and setting. Depending on your input mpd will be configured, desktop-files are created and necessary python-packages getting installed.\n"
"Please be patient while an installation-processs is running and do not kill the process while installing to avoid damage to the system.\n"
"\n"
"If you want to support the project and help developing than visit the project-site at github.com", None))
        self.pB_abort.setText(_translate("Installation_Guide", "Abort", None))
        self.pB_previouse.setText(_translate("Installation_Guide", "Previouse", None))
        self.pB_next.setText(_translate("Installation_Guide", "Next", None))
        self.pB_finished.setText(_translate("Installation_Guide", "Finished!", None))

from lib.LM_Widgets_scaled_contents import Scaling_QLabel_pixmap
